import { Availability, PrismaClient, ProductionStyle } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding database...");

  // Wipe in dependency order
  await prisma.award.deleteMany();
  await prisma.productImage.deleteMany();
  await prisma.product.deleteMany();
  await prisma.category.deleteMany();

  const [bourbonCat, ryeCat, pappyCat, limitedCat, infusedCat] = await Promise.all([
    prisma.category.create({
      data: {
        slug: "bourbon",
        name: "Bourbon",
        description: "Kentucky straight bourbon — at least 51% corn, aged in new charred American oak.",
        sortOrder: 1,
      },
    }),
    prisma.category.create({
      data: {
        slug: "rye",
        name: "Rye Whiskey",
        description: "Spicy, bold whiskeys made from at least 51% rye grain.",
        sortOrder: 2,
      },
    }),
    prisma.category.create({
      data: {
        slug: "pappy",
        name: "Pappy Van Winkle",
        description: "The legendary wheated bourbon. Heavily allocated. Patiently aged. The crown jewel of any collection.",
        sortOrder: 3,
      },
    }),
    prisma.category.create({
      data: {
        slug: "limited-edition",
        name: "Limited Edition",
        description: "Rare, allocated bottlings hand-selected by our Master Distiller.",
        sortOrder: 4,
      },
    }),
    prisma.category.create({
      data: {
        slug: "infused",
        name: "Infused & Flavored",
        description: "Naturally infused expressions for the curious palate.",
        sortOrder: 5,
      },
    }),
  ]);

  const products = [
    {
      slug: "bourbon-oak-reserve-12",
      name: "Bourbon & Oak Reserve",
      subtitle: "12 Year Kentucky Straight Bourbon",
      description:
        "Our flagship reserve, aged a full twelve years in deeply charred American white oak. A masterpiece of patience.",
      story:
        "Selected from the heart of our rickhouse, where temperature swings coax richer flavor from the barrel.",
      bottlePrice: 89.99,
      casePrice: 485.0,
      bottlesPerCase: 6,
      compareAtPrice: 99.99,
      ageYears: 12,
      proof: 92.0,
      abv: 46.0,
      cornPercent: 70,
      ryePercent: 21,
      maltedBarleyPct: 9,
      distillery: "Bourbon & Oak Distillery",
      region: "Kentucky",
      state: "KY",
      masterDistiller: "Eleanor Hayes",
      caskType: "New American White Oak",
      charLevel: 4,
      productionStyle: ProductionStyle.SMALL_BATCH,
      isFeatured: true,
      badge: "Best Seller",
      sku: "BOR-12-750",
      stockBottles: 240,
      stockCases: 18,
      rating: 4.8,
      reviewCount: 234,
      nose: "Caramel, vanilla, baked apple",
      palate: "Toffee, oak spice, dark cherry",
      finish: "Long, warm, with a whisper of leather",
      flavorTags: ["caramel", "oak", "vanilla", "spice"],
      categoryId: bourbonCat.id,
      images: [
        "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=900&q=80",
        "https://images.unsplash.com/photo-1551731409-43eb3e517a1a?w=900&q=80",
        "https://images.unsplash.com/photo-1560148218-1a83060f7b32?w=900&q=80",
        "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=900&q=80",
      ],
      awards: [
        { name: "Double Gold", organization: "San Francisco World Spirits Competition", year: 2024, medal: "Double Gold" },
      ],
    },
    {
      slug: "small-batch-select-8",
      name: "Small Batch Select",
      subtitle: "8 Year Small Batch",
      description: "A balanced small batch selected from no more than 20 barrels per release.",
      bottlePrice: 64.99,
      casePrice: 359.0,
      bottlesPerCase: 6,
      ageYears: 8,
      proof: 90.0,
      abv: 45.0,
      cornPercent: 75,
      ryePercent: 18,
      maltedBarleyPct: 7,
      distillery: "Bourbon & Oak Distillery",
      region: "Kentucky",
      state: "KY",
      caskType: "New American White Oak",
      charLevel: 3,
      productionStyle: ProductionStyle.SMALL_BATCH,
      isFeatured: true,
      sku: "SBS-08-750",
      stockBottles: 412,
      stockCases: 30,
      rating: 4.6,
      reviewCount: 189,
      nose: "Honey, almond, light citrus",
      palate: "Smooth caramel, brown sugar, gentle pepper",
      finish: "Medium, clean, slightly sweet",
      flavorTags: ["honey", "almond", "caramel"],
      categoryId: bourbonCat.id,
      images: [
        "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=900&q=80",
        "https://images.unsplash.com/photo-1582819509237-d6ad1f0ca8e9?w=900&q=80",
        "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=900&q=80",
      ],
      awards: [],
    },
    {
      slug: "single-barrel-cask-10",
      name: "Single Barrel Cask",
      subtitle: "10 Year Single Barrel",
      description: "One barrel. One bottling. Each release uniquely numbered and dated.",
      bottlePrice: 109.99,
      casePrice: 599.0,
      bottlesPerCase: 6,
      ageYears: 10,
      proof: 100.0,
      abv: 50.0,
      cornPercent: 72,
      ryePercent: 21,
      maltedBarleyPct: 7,
      distillery: "Bourbon & Oak Distillery",
      region: "Kentucky",
      state: "KY",
      caskType: "New American White Oak",
      charLevel: 4,
      barrelNumber: "B-2014-377",
      productionStyle: ProductionStyle.SINGLE_BARREL,
      isFeatured: true,
      isLimitedEdition: false,
      badge: "Limited",
      sku: "SBC-10-750",
      stockBottles: 96,
      stockCases: 8,
      rating: 4.9,
      reviewCount: 156,
      nose: "Dark chocolate, toasted oak, ripe fig",
      palate: "Rich and oily — caramel, espresso, baking spice",
      finish: "Long, warm, lingering oak tannin",
      flavorTags: ["chocolate", "espresso", "fig", "spice"],
      categoryId: bourbonCat.id,
      images: [
        "https://images.unsplash.com/photo-1609951651556-5334e2706168?w=900&q=80",
        "https://images.unsplash.com/photo-1574671928146-5c89a8aac81d?w=900&q=80",
        "https://images.unsplash.com/photo-1614313511387-1436a4480ebb?w=900&q=80",
        "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=900&q=80",
      ],
      awards: [
        { name: "Gold", organization: "International Wine & Spirit Competition", year: 2023, medal: "Gold" },
      ],
    },
    {
      slug: "heritage-1876-15",
      name: "Heritage 1876",
      subtitle: "15 Year Heritage Reserve",
      description:
        "A tribute to the year our distillery was founded. Aged fifteen years and bottled at full cask character.",
      bottlePrice: 149.99,
      casePrice: 825.0,
      bottlesPerCase: 6,
      ageYears: 15,
      proof: 96.0,
      abv: 48.0,
      cornPercent: 68,
      ryePercent: 24,
      maltedBarleyPct: 8,
      distillery: "Bourbon & Oak Distillery",
      region: "Kentucky",
      state: "KY",
      caskType: "New American White Oak",
      charLevel: 4,
      productionStyle: ProductionStyle.SMALL_BATCH,
      isFeatured: true,
      badge: "Premium",
      sku: "HER-15-750",
      stockBottles: 64,
      stockCases: 4,
      availability: Availability.LOW_STOCK,
      rating: 4.9,
      reviewCount: 98,
      nose: "Aged leather, pipe tobacco, dark stone fruit",
      palate: "Layered — toffee, walnut, candied orange peel",
      finish: "Exceptionally long with sweet oak and dried fig",
      flavorTags: ["leather", "tobacco", "stone fruit", "walnut"],
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      categoryId: bourbonCat.id,
      images: [
        "https://images.unsplash.com/photo-1578911373434-0cb395d2cbfb?w=900&q=80",
        "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=900&q=80",
        "https://images.unsplash.com/photo-1582819509237-d6ad1f0ca8e9?w=900&q=80",
        "https://images.unsplash.com/photo-1551731409-43eb3e517a1a?w=900&q=80",
      ],
      awards: [
        { name: "Best Bourbon 15+", organization: "World Whiskies Awards", year: 2024, medal: "Gold" },
      ],
    },
    {
      slug: "honey-infused-6",
      name: "Honey Infused",
      subtitle: "6 Year Honey Infused Bourbon",
      description: "Bourbon mellowed with wildflower honey from Kentucky apiaries.",
      bottlePrice: 44.99,
      casePrice: 479.0,
      bottlesPerCase: 12,
      ageYears: 6,
      proof: 70.0,
      abv: 35.0,
      cornPercent: 78,
      ryePercent: 14,
      maltedBarleyPct: 8,
      distillery: "Bourbon & Oak Distillery",
      region: "Kentucky",
      state: "KY",
      caskType: "New American White Oak",
      charLevel: 3,
      productionStyle: ProductionStyle.STANDARD,
      isFeatured: true,
      badge: "Popular",
      sku: "HON-06-750",
      stockBottles: 538,
      stockCases: 42,
      rating: 4.5,
      reviewCount: 312,
      nose: "Wildflower honey, vanilla bean",
      palate: "Sweet and round — honeycomb, light oak, soft spice",
      finish: "Smooth and gentle, lingering sweetness",
      flavorTags: ["honey", "vanilla", "smooth"],
      categoryId: infusedCat.id,
      images: [
        "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=900&q=80",
        "https://images.unsplash.com/photo-1560148218-1a83060f7b32?w=900&q=80",
        "https://images.unsplash.com/photo-1574671928146-5c89a8aac81d?w=900&q=80",
      ],
      awards: [],
    },
    {
      slug: "rye-whiskey-blend-7",
      name: "Rye Whiskey Blend",
      subtitle: "7 Year High-Rye",
      description: "A bold high-rye expression with assertive spice and a long, dry finish.",
      bottlePrice: 54.99,
      casePrice: 299.0,
      bottlesPerCase: 6,
      ageYears: 7,
      proof: 95.0,
      abv: 47.5,
      cornPercent: 39,
      ryePercent: 55,
      maltedBarleyPct: 6,
      distillery: "Bourbon & Oak Distillery",
      region: "Kentucky",
      state: "KY",
      caskType: "New American White Oak",
      charLevel: 4,
      productionStyle: ProductionStyle.SMALL_BATCH,
      isFeatured: true,
      sku: "RYE-07-750",
      stockBottles: 318,
      stockCases: 24,
      rating: 4.7,
      reviewCount: 201,
      nose: "Black pepper, mint, citrus zest",
      palate: "Spicy and dry — clove, dark rye bread, candied ginger",
      finish: "Long, peppery, with cooling menthol",
      flavorTags: ["spice", "pepper", "mint", "citrus"],
      categoryId: ryeCat.id,
      images: [
        "https://images.unsplash.com/photo-1614313511387-1436a4480ebb?w=900&q=80",
        "https://images.unsplash.com/photo-1619451334792-150fd785ee74?w=900&q=80",
        "https://images.unsplash.com/photo-1574671928146-5c89a8aac81d?w=900&q=80",
        "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=900&q=80",
      ],
      awards: [],
    },
    {
      slug: "bottled-in-bond-4",
      name: "Bottled in Bond",
      subtitle: "4 Year Bottled-in-Bond",
      description: "100 proof, single distillery, single season — to the letter of the Bottled-in-Bond Act of 1897.",
      bottlePrice: 39.99,
      casePrice: 429.0,
      bottlesPerCase: 12,
      ageYears: 4,
      proof: 100.0,
      abv: 50.0,
      cornPercent: 75,
      ryePercent: 18,
      maltedBarleyPct: 7,
      distillery: "Bourbon & Oak Distillery",
      region: "Kentucky",
      state: "KY",
      caskType: "New American White Oak",
      charLevel: 3,
      productionStyle: ProductionStyle.BOTTLED_IN_BOND,
      isFeatured: true,
      badge: "Value",
      sku: "BIB-04-750",
      stockBottles: 612,
      stockCases: 48,
      rating: 4.4,
      reviewCount: 278,
      nose: "Vanilla, fresh corn bread, light caramel",
      palate: "Straightforward and warming — caramel, oak, mild spice",
      finish: "Medium, clean, classic bourbon character",
      flavorTags: ["vanilla", "caramel", "classic"],
      categoryId: bourbonCat.id,
      images: [
        "https://images.unsplash.com/photo-1619451334792-150fd785ee74?w=900&q=80",
        "https://images.unsplash.com/photo-1551731409-43eb3e517a1a?w=900&q=80",
        "https://images.unsplash.com/photo-1582819509237-d6ad1f0ca8e9?w=900&q=80",
      ],
      awards: [],
    },
    {
      slug: "master-distillers-pick-18",
      name: "Master Distiller's Pick",
      subtitle: "18 Year Allocated Release",
      description:
        "An allocated annual release, hand-chosen by our Master Distiller from the oldest barrels in the rickhouse.",
      bottlePrice: 249.99,
      casePrice: 719.0,
      bottlesPerCase: 3,
      ageYears: 18,
      proof: 110.0,
      abv: 55.0,
      cornPercent: 65,
      ryePercent: 27,
      maltedBarleyPct: 8,
      distillery: "Bourbon & Oak Distillery",
      region: "Kentucky",
      state: "KY",
      masterDistiller: "Eleanor Hayes",
      caskType: "New American White Oak",
      charLevel: 4,
      productionStyle: ProductionStyle.BARREL_PROOF,
      isFeatured: true,
      isAllocated: true,
      badge: "Rare",
      sku: "MDP-18-750",
      stockBottles: 24,
      stockCases: 0,
      availability: Availability.ALLOCATED,
      rating: 5.0,
      reviewCount: 42,
      nose: "Polished oak, dark chocolate, dried apricot",
      palate: "Concentrated — bitter cocoa, candied pecan, oak resin",
      finish: "Exceptionally long, oily, lingering dark fruit",
      flavorTags: ["oak", "chocolate", "dried fruit", "barrel proof"],
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      categoryId: bourbonCat.id,
      images: [
        "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=900&q=80",
        "https://images.unsplash.com/photo-1578911373434-0cb395d2cbfb?w=900&q=80",
        "https://images.unsplash.com/photo-1609951651556-5334e2706168?w=900&q=80",
        "https://images.unsplash.com/photo-1551731409-43eb3e517a1a?w=900&q=80",
      ],
      awards: [
        { name: "Master", organization: "The Spirits Business Bourbon Masters", year: 2024, medal: "Master" },
        { name: "Best in Class", organization: "American Whiskey Awards", year: 2023, medal: "Gold" },
      ],
    },
    {
      slug: "limited-edition-20yr",
      name: "Limited Edition 20 Year",
      subtitle: "Master Distiller's 20 Year Cask",
      description:
        "Hand-selected barrels aged a full twenty years. Bottled at barrel proof. Only 500 bottles released.",
      story:
        "A once-in-a-generation bourbon. Each barrel rested in the warmest corner of the rickhouse for two decades.",
      bottlePrice: 399.0,
      casePrice: 1149.0,
      bottlesPerCase: 3,
      compareAtPrice: 499.0,
      ageYears: 20,
      proof: 126.4,
      abv: 63.2,
      cornPercent: 70,
      ryePercent: 22,
      maltedBarleyPct: 8,
      distillery: "Bourbon & Oak Distillery",
      region: "Kentucky",
      state: "KY",
      masterDistiller: "Eleanor Hayes",
      caskType: "New American White Oak",
      charLevel: 4,
      productionStyle: ProductionStyle.BARREL_PROOF,
      isFeatured: false,
      isLimitedEdition: true,
      isAllocated: true,
      isChillFiltered: false,
      totalBottlesProduced: 500,
      badge: "Limited",
      sku: "LE-20-750",
      stockBottles: 280,
      stockCases: 0,
      availability: Availability.LOW_STOCK,
      rating: 4.9,
      reviewCount: 18,
      nose: "Antique oak, dark molasses, leather, dried tobacco",
      palate: "Massive — black tea, candied orange, dark chocolate, charred oak",
      finish: "Endless. Oak, dark fruit, and a faint note of pipe smoke",
      flavorTags: ["oak", "molasses", "leather", "tobacco", "barrel proof"],
      servingSuggestion: "Neat, in a Glencairn, with a single drop of cool water.",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      categoryId: limitedCat.id,
      images: [
        "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=900&q=80",
        "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=900&q=80",
        "https://images.unsplash.com/photo-1578911373434-0cb395d2cbfb?w=900&q=80",
        "https://images.unsplash.com/photo-1582819509237-d6ad1f0ca8e9?w=900&q=80",
      ],
      awards: [
        { name: "98 Points", organization: "Whisky Advocate", year: 2024, medal: "98" },
      ],
    },
    {
      slug: "pappy-van-winkle-15",
      name: "Pappy Van Winkle 15 Year",
      subtitle: "Family Reserve · 15 Year Wheated Bourbon",
      description:
        "The entry into the Pappy lineage. Fifteen patient years in oak yield a soft, sweet, profoundly drinkable wheated bourbon.",
      story:
        "Wheat replaces rye in the mash bill, smoothing the spice and letting honeyed notes step forward. Heavily allocated. Patiently rewarded.",
      bottlePrice: 599.0,
      casePrice: 1699.0,
      bottlesPerCase: 3,
      compareAtPrice: 749.0,
      ageYears: 15,
      proof: 107.0,
      abv: 53.5,
      cornPercent: 70,
      wheatPercent: 18,
      maltedBarleyPct: 12,
      distillery: "Buffalo Trace · Van Winkle Reserve",
      region: "Kentucky",
      state: "KY",
      masterDistiller: "Julian Van Winkle III",
      caskType: "New American White Oak",
      charLevel: 4,
      productionStyle: ProductionStyle.SMALL_BATCH,
      isFeatured: false,
      isLimitedEdition: true,
      isAllocated: true,
      isChillFiltered: false,
      badge: "Allocated",
      sku: "PVW-15-750",
      stockBottles: 12,
      stockCases: 0,
      availability: Availability.ALLOCATED,
      rating: 4.9,
      reviewCount: 84,
      nose: "Honey, vanilla, toasted almond",
      palate: "Soft caramel, baking spice, brown sugar",
      finish: "Long, sweet, lingering oak",
      flavorTags: ["honey", "wheat", "caramel", "vanilla"],
      categoryId: pappyCat.id,
      images: [
        "https://images.unsplash.com/photo-1582819509237-d6ad1f0ca8e9?w=900&q=80",
        "https://images.unsplash.com/photo-1574671928146-5c89a8aac81d?w=900&q=80",
        "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=900&q=80",
      ],
      awards: [
        { name: "Gold", organization: "San Francisco World Spirits", year: 2023, medal: "Gold" },
      ],
    },
    {
      slug: "pappy-van-winkle-20",
      name: "Pappy Van Winkle 20 Year",
      subtitle: "Family Reserve · 20 Year Wheated Bourbon",
      description:
        "Twenty years in charred oak. The middle child of the Pappy lineup — concentrated, complex, and unmistakable.",
      story:
        "An additional five years over the 15 deepens every flavor — leather, dark fruit, and exquisite oak integration.",
      bottlePrice: 1499.0,
      casePrice: 4199.0,
      bottlesPerCase: 3,
      compareAtPrice: 1799.0,
      ageYears: 20,
      proof: 90.4,
      abv: 45.2,
      cornPercent: 70,
      wheatPercent: 18,
      maltedBarleyPct: 12,
      distillery: "Buffalo Trace · Van Winkle Reserve",
      region: "Kentucky",
      state: "KY",
      masterDistiller: "Julian Van Winkle III",
      caskType: "New American White Oak",
      charLevel: 4,
      productionStyle: ProductionStyle.SMALL_BATCH,
      isFeatured: false,
      isLimitedEdition: true,
      isAllocated: true,
      isChillFiltered: false,
      totalBottlesProduced: 1200,
      badge: "Rare",
      sku: "PVW-20-750",
      stockBottles: 6,
      stockCases: 0,
      availability: Availability.ALLOCATED,
      rating: 5.0,
      reviewCount: 47,
      nose: "Leather, dark cherry, polished oak",
      palate: "Dense — dark caramel, dried fig, espresso, baking spice",
      finish: "Exceptionally long, oily, with cocoa and oak resin",
      flavorTags: ["leather", "dark fruit", "espresso", "oak"],
      categoryId: pappyCat.id,
      images: [
        "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=900&q=80",
        "https://images.unsplash.com/photo-1582819509237-d6ad1f0ca8e9?w=900&q=80",
        "https://images.unsplash.com/photo-1578911373434-0cb395d2cbfb?w=900&q=80",
        "https://images.unsplash.com/photo-1551731409-43eb3e517a1a?w=900&q=80",
      ],
      awards: [
        { name: "97 Points", organization: "Whisky Advocate", year: 2023, medal: "97" },
        { name: "Double Gold", organization: "San Francisco World Spirits", year: 2024, medal: "Double Gold" },
      ],
    },
    {
      slug: "pappy-van-winkle-23",
      name: "Pappy Van Winkle 23 Year",
      subtitle: "Family Reserve · 23 Year Wheated Bourbon",
      description:
        "The crown jewel. Twenty-three years coaxing flavor from oak — a once-in-a-generation wheated bourbon, and the most coveted bottle in American whiskey.",
      story:
        "Two decades and three years in the rickhouse. Fewer than a thousand bottles a year. The pinnacle of the Van Winkle family's craft, and the most allocated bottle on this site.",
      bottlePrice: 2999.0,
      casePrice: 8499.0,
      bottlesPerCase: 3,
      compareAtPrice: 3499.0,
      ageYears: 23,
      proof: 95.6,
      abv: 47.8,
      cornPercent: 70,
      wheatPercent: 18,
      maltedBarleyPct: 12,
      distillery: "Buffalo Trace · Van Winkle Reserve",
      region: "Kentucky",
      state: "KY",
      masterDistiller: "Julian Van Winkle III",
      caskType: "New American White Oak",
      charLevel: 4,
      productionStyle: ProductionStyle.SMALL_BATCH,
      isFeatured: false,
      isLimitedEdition: true,
      isAllocated: true,
      isChillFiltered: false,
      totalBottlesProduced: 800,
      badge: "Crown Jewel",
      sku: "PVW-23-750",
      stockBottles: 3,
      stockCases: 0,
      availability: Availability.ALLOCATED,
      rating: 5.0,
      reviewCount: 31,
      nose: "Antique leather, sandalwood, dark molasses, dried apricot",
      palate: "Profound — old oak, dark cocoa, candied orange peel, pipe tobacco",
      finish: "Eternal. Sweet oak, dried fruit, and a whisper of smoke",
      flavorTags: ["oak", "leather", "molasses", "tobacco", "wheated"],
      servingSuggestion: "Neat, in a Glencairn glass. No water needed.",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      categoryId: pappyCat.id,
      images: [
        "https://images.unsplash.com/photo-1578911373434-0cb395d2cbfb?w=900&q=80",
        "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=900&q=80",
        "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=900&q=80",
        "https://images.unsplash.com/photo-1582819509237-d6ad1f0ca8e9?w=900&q=80",
      ],
      awards: [
        { name: "99 Points", organization: "Whisky Advocate", year: 2024, medal: "99" },
        { name: "Master", organization: "The Spirits Business Bourbon Masters", year: 2024, medal: "Master" },
        { name: "Best in Show", organization: "World Whiskies Awards", year: 2023, medal: "Gold" },
      ],
    },
  ];

  for (const p of products) {
    const { images, awards, ...data } = p;
    await prisma.product.create({
      data: {
        ...data,
        images: {
          create: images.map((url, idx) => ({
            url,
            alt: p.name,
            sortOrder: idx,
            isPrimary: idx === 0,
          })),
        },
        awards: {
          create: awards,
        },
      },
    });
    console.log(`  + ${p.name}`);
  }

  const productCount = await prisma.product.count();
  const categoryCount = await prisma.category.count();
  console.log(`Done. ${categoryCount} categories, ${productCount} products.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
